### ISSUE TITLE
Cannot update the MAX SPEED/ACCELERATE FOR STEP/TIMEOUT

### ISSUE THREAD

**Issue by bdudout** [FarmBot/farmbot_os#284]
* Farmbot OS version: Version3.0.8-rc.8 (latest currently)
  * Website tested : both my.farmbot.io and staging.farmbot.io

### Step 3: Describe the problem:

In the form DEVICE > HARDWARE it is only possible to update STEPS PER MM and the toggle buttons.

The following fields are not able to update the value : MAX SPEED/ACCELERATE FOR STEP/TIMEOUT

#### Steps to reproduce:

  1. Connect to the website (either my or staging)
  2. Go to DEVICE > HARDWARE
  3. Update values for MAX SPEED/ACCELERATE FOR STEP/TIMEOUT
  4. Save

#### Observed Results:

The values are going back to their previous value (not especially the default one, the previous one)

#### Expected Results:

Values should update (working for the steps per mm)

Do not hesitate to ask me for more testing !
Thanks :)

**Comment by dwhickox** [comment]
This has been a known issue for quite a while, I have been having this problem for a long time, as far as I am aware they are currently working on implementing all the buttons and settings into the software, but the web interface was developed long before the functionality was there. So this might not be a "bug" since I don't know if there is even code in the OS to make it work, but I am a couple of weeks behind on their progress. If it has been "fixed" then count me in on it doesn't work for me either.

**Comment by ConnorRigby** [comment]
Do the toggle buttons work? 
I think this might be a bug in two places.
Investigating today.

**Comment by bdudout** [comment]
Yes, toggle buttons are ok :)

**Comment by ConnorRigby** [comment]
Sorry we havent had time too look more into this in full. I believe i know what is going on tho.

**Comment by ConnorRigby** [comment]
@bdudout i believe this to be fixed in our staging environment. Should be up soon on production.

**Comment by ConnorRigby** [comment]
@bdudout hopefully you can confirm this is fixed now.
