### ISSUE TITLE
when will release stable version of 6.x

### ISSUE THREAD

**Issue by snzip** [FarmBot/farmbot_os#488]
the recent release only include *.fw bundle. 
When will release a stable version including *.img bundle? 
thanks,

**Comment by ConnorRigby** [comment]
You can download the latest img file, and upgrade. The reason for only publishing the *.fw files, is because there is a lot of migration code between releases, and releasing an image file would skip running that migration code, and make initial startup of FarmbotOS unstable/impossible.

the latest `6.3.1` is _stable_, you just need to flash the initial `6.0.1` image too bootstrap into the latest stable release.
